# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'os_translator_ii_dialog_base.ui'
#
# Created: Tue May 19 12:21:33 2015
#      by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.setEnabled(True)
        Dialog.resize(849, 326)
        self.gridLayout_4 = QtGui.QGridLayout(Dialog)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.simultaneousJobsSpinBox = QtGui.QSpinBox(Dialog)
        self.simultaneousJobsSpinBox.setMinimum(1)
        self.simultaneousJobsSpinBox.setMaximum(128)
        self.simultaneousJobsSpinBox.setProperty(_fromUtf8("value"), 2)
        self.simultaneousJobsSpinBox.setObjectName(_fromUtf8("simultaneousJobsSpinBox"))
        self.gridLayout.addWidget(self.simultaneousJobsSpinBox, 4, 2, 1, 2)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 2)
        self.deleteTaskPushButton = QtGui.QPushButton(Dialog)
        self.deleteTaskPushButton.setEnabled(False)
        self.deleteTaskPushButton.setObjectName(_fromUtf8("deleteTaskPushButton"))
        self.gridLayout.addWidget(self.deleteTaskPushButton, 2, 1, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 0, 1, 1)
        self.newTaskPushButton = QtGui.QPushButton(Dialog)
        self.newTaskPushButton.setEnabled(False)
        self.newTaskPushButton.setObjectName(_fromUtf8("newTaskPushButton"))
        self.gridLayout.addWidget(self.newTaskPushButton, 2, 3, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.line_2 = QtGui.QFrame(Dialog)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.gridLayout.addWidget(self.line_2, 3, 0, 1, 4)
        self.tasksListWidget = QtGui.QListWidget(Dialog)
        self.tasksListWidget.setObjectName(_fromUtf8("tasksListWidget"))
        self.gridLayout.addWidget(self.tasksListWidget, 1, 0, 1, 4)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.line = QtGui.QFrame(Dialog)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.gridLayout_4.addWidget(self.line, 0, 1, 1, 1)
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_8 = QtGui.QLabel(Dialog)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.postgisConnectionComboBox = QtGui.QComboBox(Dialog)
        self.postgisConnectionComboBox.setObjectName(_fromUtf8("postgisConnectionComboBox"))
        self.gridLayout_2.addWidget(self.postgisConnectionComboBox, 3, 1, 1, 2)
        self.labelLineEdit = QtGui.QLineEdit(Dialog)
        self.labelLineEdit.setText(_fromUtf8(""))
        self.labelLineEdit.setObjectName(_fromUtf8("labelLineEdit"))
        self.gridLayout_2.addWidget(self.labelLineEdit, 0, 1, 1, 2)
        self.inputLineEdit = QtGui.QLineEdit(Dialog)
        self.inputLineEdit.setMinimumSize(QtCore.QSize(120, 0))
        self.inputLineEdit.setObjectName(_fromUtf8("inputLineEdit"))
        self.gridLayout_2.addWidget(self.inputLineEdit, 12, 1, 1, 1)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.modeComboBox = QtGui.QComboBox(Dialog)
        self.modeComboBox.setEnabled(False)
        self.modeComboBox.setObjectName(_fromUtf8("modeComboBox"))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.modeComboBox.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.modeComboBox, 4, 1, 1, 2)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.datasetComboBox = QtGui.QComboBox(Dialog)
        self.datasetComboBox.setObjectName(_fromUtf8("datasetComboBox"))
        self.gridLayout_2.addWidget(self.datasetComboBox, 1, 1, 1, 2)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.inputLabel = QtGui.QLabel(Dialog)
        self.inputLabel.setObjectName(_fromUtf8("inputLabel"))
        self.gridLayout_2.addWidget(self.inputLabel, 12, 0, 1, 1)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.batchModeCheckBox = QtGui.QCheckBox(Dialog)
        self.batchModeCheckBox.setEnabled(False)
        self.batchModeCheckBox.setChecked(True)
        self.batchModeCheckBox.setObjectName(_fromUtf8("batchModeCheckBox"))
        self.gridLayout_2.addWidget(self.batchModeCheckBox, 9, 0, 1, 3)
        self.destSchema = QtGui.QLineEdit(Dialog)
        self.destSchema.setObjectName(_fromUtf8("destSchema"))
        self.gridLayout_2.addWidget(self.destSchema, 5, 1, 1, 2)
        self.browsePushButton = QtGui.QPushButton(Dialog)
        self.browsePushButton.setMaximumSize(QtCore.QSize(30, 16777215))
        self.browsePushButton.setObjectName(_fromUtf8("browsePushButton"))
        self.gridLayout_2.addWidget(self.browsePushButton, 12, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 13, 1, 1, 1)
        self.line_3 = QtGui.QFrame(Dialog)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.gridLayout_2.addWidget(self.line_3, 2, 0, 1, 3)
        self.line_4 = QtGui.QFrame(Dialog)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.gridLayout_2.addWidget(self.line_4, 8, 0, 1, 3)
        self.createSpatialIndexCheckBox = QtGui.QCheckBox(Dialog)
        self.createSpatialIndexCheckBox.setChecked(True)
        self.createSpatialIndexCheckBox.setObjectName(_fromUtf8("createSpatialIndexCheckBox"))
        self.gridLayout_2.addWidget(self.createSpatialIndexCheckBox, 6, 0, 1, 3)
        self.removeDuplicatesCheckBox = QtGui.QCheckBox(Dialog)
        self.removeDuplicatesCheckBox.setToolTip(_fromUtf8(""))
        self.removeDuplicatesCheckBox.setStatusTip(_fromUtf8(""))
        self.removeDuplicatesCheckBox.setChecked(True)
        self.removeDuplicatesCheckBox.setObjectName(_fromUtf8("removeDuplicatesCheckBox"))
        self.gridLayout_2.addWidget(self.removeDuplicatesCheckBox, 7, 0, 1, 3)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 2, 1, 1)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_9 = QtGui.QLabel(Dialog)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 0, 0, 1, 1)
        self.fieldsTreeWidget = QtGui.QTreeWidget(Dialog)
        self.fieldsTreeWidget.setMinimumSize(QtCore.QSize(354, 0))
        self.fieldsTreeWidget.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.fieldsTreeWidget.setObjectName(_fromUtf8("fieldsTreeWidget"))
        self.fieldsTreeWidget.headerItem().setText(0, _fromUtf8("1"))
        self.fieldsTreeWidget.header().setVisible(False)
        self.gridLayout_3.addWidget(self.fieldsTreeWidget, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 3, 1, 3)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.helpPushButton = QtGui.QPushButton(Dialog)
        self.helpPushButton.setEnabled(True)
        self.helpPushButton.setObjectName(_fromUtf8("helpPushButton"))
        self.horizontalLayout.addWidget(self.helpPushButton)
        self.aboutPushButton = QtGui.QPushButton(Dialog)
        self.aboutPushButton.setEnabled(False)
        self.aboutPushButton.setObjectName(_fromUtf8("aboutPushButton"))
        self.horizontalLayout.addWidget(self.aboutPushButton)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_4.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(Dialog)
        self.progressBar.setEnabled(False)
        self.progressBar.setMaximum(99)
        self.progressBar.setProperty(_fromUtf8("value"), 0)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_4.addWidget(self.progressBar, 1, 2, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 1, 5, 1, 1)
        self.statusLabel = QtGui.QLabel(Dialog)
        self.statusLabel.setObjectName(_fromUtf8("statusLabel"))
        self.gridLayout_4.addWidget(self.statusLabel, 1, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), Dialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), Dialog.reject)
        QtCore.QObject.connect(self.browsePushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.browseForInput)
        QtCore.QObject.connect(self.simultaneousJobsSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), Dialog.storeSettings)
        QtCore.QObject.connect(self.datasetComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.storeSettings)
        QtCore.QObject.connect(self.postgisConnectionComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.storeSettings)
        QtCore.QObject.connect(self.modeComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.storeSettings)
        QtCore.QObject.connect(self.destSchema, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), Dialog.storeSettings)
        QtCore.QObject.connect(self.datasetComboBox, QtCore.SIGNAL(_fromUtf8("currentIndexChanged(int)")), Dialog.updateFieldsList)
        QtCore.QObject.connect(self.helpPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.helpPressed)
        QtCore.QObject.connect(self.aboutPushButton, QtCore.SIGNAL(_fromUtf8("clicked()")), Dialog.aboutPressed)
        QtCore.QObject.connect(self.createSpatialIndexCheckBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Dialog.storeSettings)
        QtCore.QObject.connect(self.removeDuplicatesCheckBox, QtCore.SIGNAL(_fromUtf8("stateChanged(int)")), Dialog.storeSettings)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tasksListWidget, self.deleteTaskPushButton)
        Dialog.setTabOrder(self.deleteTaskPushButton, self.newTaskPushButton)
        Dialog.setTabOrder(self.newTaskPushButton, self.simultaneousJobsSpinBox)
        Dialog.setTabOrder(self.simultaneousJobsSpinBox, self.labelLineEdit)
        Dialog.setTabOrder(self.labelLineEdit, self.datasetComboBox)
        Dialog.setTabOrder(self.datasetComboBox, self.postgisConnectionComboBox)
        Dialog.setTabOrder(self.postgisConnectionComboBox, self.modeComboBox)
        Dialog.setTabOrder(self.modeComboBox, self.destSchema)
        Dialog.setTabOrder(self.destSchema, self.batchModeCheckBox)
        Dialog.setTabOrder(self.batchModeCheckBox, self.inputLineEdit)
        Dialog.setTabOrder(self.inputLineEdit, self.browsePushButton)
        Dialog.setTabOrder(self.browsePushButton, self.buttonBox)
        Dialog.setTabOrder(self.buttonBox, self.fieldsTreeWidget)
        Dialog.setTabOrder(self.fieldsTreeWidget, self.helpPushButton)
        Dialog.setTabOrder(self.helpPushButton, self.aboutPushButton)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "OS Translator II", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Processor Cores", None, QtGui.QApplication.UnicodeUTF8))
        self.deleteTaskPushButton.setText(QtGui.QApplication.translate("Dialog", "Delete", None, QtGui.QApplication.UnicodeUTF8))
        self.newTaskPushButton.setText(QtGui.QApplication.translate("Dialog", "New", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Import Tasks", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("Dialog", "Dataset", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "Label", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(0, QtGui.QApplication.translate("Dialog", "Create or Replace", None, QtGui.QApplication.UnicodeUTF8))
        self.modeComboBox.setItemText(1, QtGui.QApplication.translate("Dialog", "Append", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Mode", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Connection", None, QtGui.QApplication.UnicodeUTF8))
        self.inputLabel.setText(QtGui.QApplication.translate("Dialog", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Schema", None, QtGui.QApplication.UnicodeUTF8))
        self.batchModeCheckBox.setText(QtGui.QApplication.translate("Dialog", "Recursively process a directory", None, QtGui.QApplication.UnicodeUTF8))
        self.browsePushButton.setText(QtGui.QApplication.translate("Dialog", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.createSpatialIndexCheckBox.setText(QtGui.QApplication.translate("Dialog", "Create spatial index", None, QtGui.QApplication.UnicodeUTF8))
        self.removeDuplicatesCheckBox.setText(QtGui.QApplication.translate("Dialog", "Remove duplicates (chunk artefacts)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("Dialog", "Fields", None, QtGui.QApplication.UnicodeUTF8))
        self.helpPushButton.setText(QtGui.QApplication.translate("Dialog", "Help", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutPushButton.setText(QtGui.QApplication.translate("Dialog", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.statusLabel.setText(QtGui.QApplication.translate("Dialog", "Status label", None, QtGui.QApplication.UnicodeUTF8))

